language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -e ".[testing]"
  - pip install -r requirements-docs.txt

script:
  - pytest
  - sphinx-build -b html docs docs/_build/html

deploy:
  local_dir: docs/_build/html
  provider: pages
  repo: MapperInteractive/website
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    python: "3.6"
    branch: master
